{{- if or .Values.daemonset.deploy .Values.delegatedAgentDeployment.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.configmapName" . }}
  namespace: {{ include "agent.namespace" . }}
  labels:
{{ (include "agent.labels" .) | indent 4 }}
data:
  dragent.yaml: |
    new_k8s: true
    {{- include "agent.clusterName" . | indent 4 }}
    {{- if .Values.delegatedAgentDeployment.enabled }}
    cointerface_enabled: false
    {{- end }}
    {{- include "agent.connectionSettings" . | indent 4 }}
    {{- include "agent.secureFeatures" . | nindent 4 }}
    {{- include "agent.k8sColdStart" . | nindent 4 }}
    {{- if .Values.sysdig.disableCaptures }}
    sysdig_capture_enabled: false
    {{- end }}
    {{/* check for log level sanity */}}
    {{- if and .Values.logPriority (or (hasKey (default dict .Values.sysdig.settings.log) "console_priority") (hasKey (default dict .Values.sysdig.settings.log) "file_priority")) }}
    {{- fail "Cannot set logPriority when either sysdig.settings.log.console_priority or sysdig.settings.log.file_priority are set" }}
    {{- end }}
    {{- if .Values.logPriority }}
    {{- $_ := merge .Values.sysdig.settings (dict "log" (dict "console_priority" .Values.logPriority "file_priority" .Values.logPriority)) }}
    {{- end }}
    {{/* add in the remaining items from sysdig.settings */}}
    {{- if .Values.sysdig.settings }}
    {{ toYaml .Values.sysdig.settings | nindent 4 }}
    {{- end }}
    {{- if .Values.global.sysdig.tags }}
    tags: {{ include "agent.tags" . }}
    {{- end }}
    {{- if .Values.prometheus.file }}
  prometheus.yaml: |
{{ toYaml .Values.prometheus.yaml | indent 4 }}
  {{- end }}
{{- end }}
