{{- if .Values.delegatedAgentDeployment.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.configmapName" . | printf "%s-deployment" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "agent.namespace" . }}
  labels:
{{ include "agent.labels" . | indent 4 }}
data:
  dragent.yaml: |
    new_k8s: true
    {{- include "agent.clusterName" . | indent 4 }}
    {{- include "agent.connectionSettings" . | nindent 4 }}
    feature:
      mode: monitor_light
    cointerface_enabled: true
    k8s_delegated_nodes: -1
    top_processes_in_sample: 0
    container_engines:
      bpm: false
      cri: false
      docker: false
      libvirt_lxc: false
      lxc: false
      mesos: false
      podman: false
      rkt: false
    app_checks_enabled: false
    jmx:
      enabled: false
    prometheus:
      enabled: false
    statsd:
      enabled: false
    {{- include "agent.k8sColdStart" . | nindent 4 }}
    {{- $_ := merge .Values.secure (dict "enabled" false) }}
    {{- include "agent.secureFeatures" . | nindent 4 }}
    {{/* check for log level sanity */}}
    {{- if and .Values.logPriority (or (hasKey (default dict .Values.sysdig.settings.log) "console_priority") (hasKey (default dict .Values.sysdig.settings.log) "file_priority")) }}
    {{- fail "Cannot set logPriority when either sysdig.settings.log.console_priority or sysdig.settings.log.file_priority are set" }}
    {{- end }}
    {{- if .Values.logPriority }}
    {{- $_ := merge .Values.sysdig.settings (dict "log" (dict "console_priority" .Values.logPriority "file_priority" .Values.logPriority)) }}
    {{- end }}
    {{- if .Values.global.sysdig.tags }}
    tags: {{ include "agent.tags" . }}
    {{- end }}
    {{/* add in the remaining items from sysdig.settings */}}
    {{- toYaml .Values.sysdig.settings | nindent 4 }}
{{- end }}
