{{- if or .Values.daemonset.deploy .Values.delegatedAgentDeployment.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.configmapName" . }}
  namespace: {{ include "agent.namespace" . }}
  labels:
{{ (include "agent.labels" .) | indent 4 }}
data:
  dragent.yaml: |
    new_k8s: true
    {{- include "agent.clusterName" . | indent 4 }}
    {{- if .Values.delegatedAgentDeployment.enabled }}
    cointerface_enabled: false
    {{- end }}
    {{- include "agent.connectionSettings" . | indent 4 }}
    {{- (include "agent.secureFeatures" (dict "root" . "force_secure_disabled" nil)) | nindent 4 }}
    {{- include "agent.k8sColdStart" . | nindent 4 }}
    {{- $disableCaptures := include "get_if_not_in_settings" (dict "root" . "default" .Values.sysdig.disableCaptures "setting" "sysdig_capture_enabled") }}
    {{- if eq $disableCaptures "true" }}
        sysdig_capture_enabled: false
    {{- end }}
    {{- include "agent.logSettings" . }}
    {{- if .Values.global.sysdig.tags }}
    tags: {{ include "agent.tags" . }}
    {{- end }}
    {{/* add in the remaining items from sysdig.settings */}}
    {{- if .Values.sysdig.settings }}
      {{- toYaml .Values.sysdig.settings | nindent 4 }}
    {{- end }}
    {{- if .Values.prometheus.file }}
  prometheus.yaml: |
{{ toYaml .Values.prometheus.yaml | indent 4 }}
  {{- end }}
{{- end }}
